[[plugins]]
repo  = 'Shougo/deoplete.nvim'
on_i  = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1

if !exists('g:deoplete#omni_patterns')
  let g:deoplete#omni_patterns = {}
endif

inoremap <expr> J pumvisible() ? "\<C-N>" : "J"
inoremap <expr> K pumvisible() ? "\<C-P>" : "K"
inoremap <expr> L pumvisible() ? "\<C-Y>" : "L"
'''
