[[plugins]]
repo = 'SirVer/ultisnips'
on_i = 1

hook_add = '''
let g:deoplete#sources={}
let g:deoplete#sources._=['buffer', 'file', 'ultisnips']
'''

hook_source = '''
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
'''

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1
