# normal plugins

# core
[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
let g:strip_whitespace_on_save = 1
'''

[[plugins]]
repo = 'kana/vim-arpeggio'
hook_add = '''
call arpeggio#load()
let g:arpeggio_timeoutlen = 60

Arpeggio inoremap jk  <Esc>
Arpeggio vnoremap jk  <Esc>
Arpeggio noremap we :w<cr>
Arpeggio noremap wq :wq<cr>
Arpeggio noremap qe :q<cr>
Arpeggio noremap q1 :q!<cr>
Arpeggio noremap ev :Files ~/.config/nvim<cr>
Arpeggio noremap rv :source $MYVIMRC<cr>:echo "Reloaded"<cr>
Arpeggio noremap vp :VimuxPromptCommand<cr>
Arpeggio noremap vo :VimuxRunLastCommand<cr><Paste>
'''

# looks n feel
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
let g:gruvbox_sign_column='bg0'
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ }
'''

# navigation
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:EasyMotion_smartcase = 1
let g:EasyMotion_startofline = 1
let g:EasyMotion_use_smartsign_us = 1

map f <plug>(easymotion-bd-f2)
map <space>w <plug>(easymotion-wl)
map <space>j <plug>(easymotion-j)
map <space>k <plug>(easymotion-k)
map <space>f <plug>(easymotion-bd-f)
'''
